name: Daily LinkedIn Job Update

on:
  schedule:
    # Runs at 2:00 pm every day
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Add any other dependencies your script needs

    - name: Add service account key
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > service_acc_key.json
        echo "open_by_key=$SPREADSHEET_KEY" > .env
      
    - name: Load LinkedIn cookies
      env:
        SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
        JSESSIONID_COOKIE: ${{ secrets.JSESSIONID_COOKIE }}
      run: |
        echo "SESSION_COOKIE=$SESSION_COOKIE" >> $GITHUB_ENV
        echo "JSESSIONID_COOKIE=$JSESSIONID_COOKIE" >> $GITHUB_ENV

    - name: Run main.py
      run: python main.py
